[20251028141057766365]
command = "claude mcp add serena -- uvx --from git+https://github.com/oraios/serena serena \ start-mcp-server --context ide-assistant --project '$(pwd)'"
tags = []
created_at = "2025-10-28T14:10:57.766424+00:00"
updated_at = "2025-10-28T14:10:57.766424+00:00"

[20251104120356163939]
command = "uv tool install --editable ."
description = "Install tool from lokal with automatic updates on change"
tags = [ "uv",]
created_at = "2025-11-04T12:03:56.163995+00:00"
updated_at = "2025-11-04T12:03:56.163995+00:00"

[20251107095239798469]
command = "unison {path1} {path2} -auto -batch"
description = "Sync dir/file"
tags = []
alias = "jj"
created_at = "2025-11-07T09:52:39.798500+00:00"
updated_at = "2025-11-08T11:25:09.894366+00:00"

[20251107103951761279]
command = "echo 'alias {alias}={content}' >> .bashrc"
description = "Create Alias"
tags = []
created_at = "2025-11-07T10:39:51.761394+00:00"
updated_at = "2025-11-07T10:39:51.761394+00:00"

[20251107152956221765]
command = "git branch --merged | grep -v \"\\*\\|main\\|master\" | xargs git branch -d"
description = "Remove merged non-main branches"
tags = []
created_at = "2025-11-07T15:29:56.222084+00:00"
updated_at = "2025-11-07T15:29:56.222084+00:00"

[20251107095239798469.parameters.path1]
name = "path1"
description = "First path"

[20251107095239798469.parameters.path2]
name = "path2"
description = "Second Path"

[20251107103951761279.parameters.alias]
name = "alias"
description = "Alias to bind"

[20251107103951761279.parameters.content]
name = "content"
description = "Content of Alias"
